spring:
  application:
    name:  tool-inventory-service

  profiles:
    default: default

  config:
    import: "configserver:"

  cloud:
    config:
      uri: http://localhost:9000

  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB
      location: /tmp
